web/Fl_e_health/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("main.urls")),
    path('patients/',include ('patients.urls')),
    path('fl/',include ('fl.urls')),
    path('hospital/',include ('hospital.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/fl/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.decorators import login_required


app_name = 'fl'

urlpatterns = [
    path('', login_required(FlHome.as_view()), name="fl"),
    path('results/', login_required(FlResultsView.as_view()), name="results"),
    path('results/<int:pk>/', login_required(FlResultView.as_view()), name="result"),
]

web/fl/models.py
from django.db import models

# Create your models here.
class FlResults(models.Model):

    ALGO_CHOICES = (
        ('Pneumonia', 'Pneumonia'),
        ('Multiclass', 'Multiclass'),
    )

    date = models.DateTimeField(auto_now_add = True)
    logs= models.TextField(blank=True, null = True)
    min_client = models.IntegerField(default=2)
    num_round = models.IntegerField(default=2)
    algo = models.CharField(max_length=10, choices=ALGO_CHOICES, default=ALGO_CHOICES[0][0])

    class Meta:
        db_table = "FlResults"

web/fl/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.views import View
from .models import *
from django.http import JsonResponse
import re
import ast

class FlHome(View):
    def get(self,req):
        if req.user.is_staff:
            return render(req,"fl/fl-main.html")
        else :
            return redirect("home")
    def post(self,req):
        res = {"status":500, "message": "There was a problem when saving fl results !"}
        try:
            data=req.POST
            logs=data.get("logs") 
            min_client=data.get("min_client")
            num_round=data.get("num_round")
            if logs and min_client and num_round:
                FlResults.objects.create(logs=logs,min_client=min_client,num_round=num_round)
                res['status'] = 200
                res['message'] = 'Fl results saved successfully'

        except Exception as e:
            print(e)
            

        return JsonResponse(res, status=res["status"])
    
class FlResultsView(View):
    def get(self,req):
        if req.user.is_staff:
            all_results=reversed(FlResults.objects.all())
            context={"all_results": []}
            for result in all_results:
                data_string = result.logs

                match = re.search(r"FL finished in (\d+\.\d+)", data_string)
                duration=0.0
                if match:
                    duration = float(match.group(1))
                    duration=int(duration)
                context["all_results"].append({"result":result,"duration":duration})                  
            return render(req,"fl/fl-results.html",context)
        else :
            return redirect("home")
        
    

class FlResultView(View,):
    def get(self,req,pk):
        if req.user.is_staff:
            result=FlResults.objects.filter(id=pk).first()

            data_string = result.logs
            
            match = re.search(r"FL finished in (\d+\.\d+)", data_string)
            duration=0.0
            duration_devided=0.0
            if match:
                duration = float(match.group(1))
                duration=int(duration)
                print(duration)
            
            losses_distributed = re.findall(r"losses_distributed \[((?:\(\d+,\s[\d.]+\),?\s?)+)\]", data_string)
            losses_distributed = [(int(round_num), float(loss)) for round_num, loss in re.findall(r"\((\d+),\s([\d.]+)\)", losses_distributed[0])] if losses_distributed else []

            training_accuracy = re.findall(r"metrics_distributed_fit {'accuracy': \[((?:\(\d+,\s[\d.]+\),?\s?)+)\]", data_string)
            training_accuracy = [(int(round_num), float(acc)) for round_num, acc in re.findall(r"\((\d+),\s([\d.]+)\)", training_accuracy[0])] if training_accuracy else []

            losses = re.findall(r"'losses': \[((?:\(\d+,\s[\d.]+\),?\s?)+)\]", data_string)
            losses = [(int(round_num), float(acc)) for round_num, acc in re.findall(r"\((\d+),\s([\d.]+)\)", losses[0])] if losses else []
            
            evaluation_accuracy = re.findall(r"metrics_distributed {'accuracy': \[((?:\(\d+,\s[\d.]+\),?\s?)+)\]}", data_string)
            evaluation_accuracy = [(int(round_num), float(acc)) for round_num, acc in re.findall(r"\((\d+),\s([\d.]+)\)", evaluation_accuracy[0])] if evaluation_accuracy else []
            duration_devided=duration/len(losses_distributed)
            rounds = []

            for i in range(len(losses_distributed)):
                round = {
                    "round": i + 1,
                    "duration":duration,
                    "losses": losses[i][1]/len(losses) if i < len(losses) else None,
                    "training_accuracy": training_accuracy[i][1] if i < len(training_accuracy) else None,
                    "evaluation_accuracy": evaluation_accuracy[i][1] if i < len(evaluation_accuracy) else None,
                }
                rounds.append(round)

            context = {"rounds": rounds,"duration":duration,"duration_devided":duration_devided,"result":result}

        
            return render(req,"fl/fl-result.html",context)
        else :
            return redirect("home")

web/templates/fl/fl-main.html
{% extends 'gui/base/base.html' %} {% load static tailwind_tags %} {% load
i18n%} {% block content %}
<div class="min-h-screen max-w-[1440px] w-full">
  <h1 class="text-third text-2xl font-bold text-center mt-8">
    Federated learning
  </h1>
  <div class="my-8 w-full flex justify-end items-center">
    <a
      href="{% url 'fl:results' %}"
      class="bg-primary text-white px-4 py-2 rounded-lg font-semibold"
      >Previous results</a
    >
  </div>
  <section class="w-full">
    <h2 class="text-xl text-third font-semibold">Training</h2>
    <div class="grid grid-cols-2 gap-x-16 w-full">
      <div class="flex jusfity-between flex-col">
        <div class="mt-4 w-full">
          <label for="algo" class="block mb-2 text-sm font-medium text-gray-900"
            >Select an algortihm</label
          >
          <!-- prettier-ignore -->
          <select id="algo"
              class="bg-gray-50 border border-gray-300 text-gray-400 text-sm rounded-lg  block w-full p-2.5  border-gray-600 placeholder-gray-400  focus:ring-blue-500 focus:border-blue-500" readonly>
              <option value="pneumonia" selected>Pneumonia</option>
            </select>
        </div>
        <div class="mt-4 w-full">
          <label
            for="min_client"
            class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
            >Min number of clients</label
          >
          <input
            type="number"
            id="min_client"
            name="min_client"
            class="bg-gray-50 border border-gray-300 text-third text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
            value="2"
          />
        </div>
        <div class="mt-4 w-full">
          <label
            for="num_round"
            class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
            >Number of rounds</label
          >
          <input
            type="number"
            id="num_round"
            name="num_round"
            class="bg-gray-50 border border-gray-300 text-third text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
            value="2"
          />
        </div>
        <button
          class="bg-primary text-white px-4 py-2 rounded w-full mt-4 font-semibold uppercase"
          onclick="startFlServer()"
        >
          Start Federated learning process
        </button>
        <a
          href="{% url 'fl:results' %}"
          class="bg-third text-white px-4 py-2 rounded w-full mt-4 font-semibold uppercase text-center"
          style="pointer-events: none; cursor: default"
          id="results_anchor"
        >
          Show results
        </a>
      </div>

      <div
        class="h-[500px] border-2 border-solid border-gray-400 px-4 py-4 overflow-auto"
      >
        <h3 class="text-third font-semibold mb-6">Logs</h3>
        <div id="output">
          <div class="h-[400px] w-full flex jusfity-center items-center">
            <span class="text-third font mx-auto"
              >Here, you can see the logs of the server</span
            >
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

{% endblock %}

web/templates/fl/fl-result.html
{% extends 'gui/base/base.html' %} {% load static tailwind_tags %} {% load
i18n%} {% block content %}
<div class="relative max-w-[1440px] w-full lg:min-h-screen-admin">
  <h1 class="text-3xl text-third font-bold text-center">
    Federated learning result : {{result.date}}
  </h1>
  <p class="mt-16 text-third text-center">
    Here is a table that summarize the results from the federated learning
    process
  </p>
  {% if rounds %}
  <table
    class="w-full text-sm text-left text-gray-500 overflow-x-auto shadow-md sm:rounded-lg mt-8"
  >
    <thead class="text-xs text-gray-700 uppercase bg-gray-50">
      <tr>
        <th scope="col" class="px-6 py-3">Round</th>
        <th scope="col" class="px-6 py-3">Duration</th>
        <th scope="col" class="px-6 py-3">Losses</th>
        <th scope="col" class="px-6 py-3">Training accuracy</th>
        <th scope="col" class="px-6 py-3">Evaluation accuracy</th>
      </tr>
    </thead>
    <tbody>
      {% for round in rounds %}
      <tr
        class="patient-row bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600"
      >
        <td
          scope="row"
          class="flex items-center px-6 py-4 text-gray-900 whitespace-nowrap dark:text-white"
        >
          <div class="text-base font-semibold" id="full_name">
            {{round.round}}
          </div>
        </td>
        <td class="px-6 py-4">{{duration_devided}} seconds</td>
        <td class="px-6 py-4">{{round.losses}}</td>
        <td class="px-6 py-4">{{round.training_accuracy}}</td>
        <td class="px-6 py-4">{{round.evaluation_accuracy}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="mt-16">
    <h2 class="text-3xl text-third font-bold">Duration</h2>
    <p class="text-third text-xl mt-16">
      <i class="fa-regular fa-clock fa-xl" style="color: #025464"></i>
      The federated learning process took
      <span class="font-bold">{{duration}} seconds</span>
    </p>
  </div>

  {% else %}
  <div
    class="flex items-center jusfity-center bg-gray-100 text-center py-4 px-4 rounded-lg"
  >
    <p class="w-full text-center font-semibold text-third">
      There is no results to be shown
    </p>
  </div>
  {% endif %}
  <h2 class="text-3xl text-third font-bold mt-16">Charts</h2>
  {% if rounds %}
  <!-- Graph for Losses -->
  <div class="max-w-[50%] mx-auto">
    <!-- Graph for Training Accuracy -->
    <div class="mt-16">
      <h2 class="text-2xl text-third font-semibold mb-4">Training Accuracy</h2>
      <p class="mb-8 text-third">
        Training accuracy measures how well a machine learning model predicts
        the labels of the training data. It shows the model's ability to
        correctly classify examples it has already seen.
      </p>
      <canvas id="trainingAccuracyChart"></canvas>
    </div>

    <!-- Graph for Evaluation Accuracy -->
    <div class="mt-16">
      <h2 class="text-2xl text-third font-semibold mb-4">
        Evaluation Accuracy
      </h2>
      <p class="mb-8 text-third">
        Test accuracy refers to the performance of a machine learning model on a
        separate dataset, called the test set, that is not used during the
        model's training phase. It measures the accuracy or correctness of the
        model's predictions on unseen data. Test accuracy provides an estimate
        of how well the model generalizes to new, unseen examples and is an
        important metric for evaluating the overall performance and
        effectiveness of the trained model.
      </p>
      <canvas id="evaluationAccuracyChart"></canvas>
    </div>
    <div class="mt-16">
      <h2 class="text-2xl text-third font-semibold mb-4">Losses</h2>
      <p class="mb-8 text-third">
        Loss refers to a numerical value that represents the error or
        discrepancy between the predicted output of a machine learning model and
        the actual ground truth. It quantifies how well the model is performing
        during the training process, with the goal of minimizing the loss over
        time. In simpler terms, loss indicates how far off the model's
        predictions are from the desired outcomes.
      </p>
      <canvas id="lossesChart"></canvas>
    </div>
    {% else %}
    <div
      class="flex items-center justify-center bg-gray-100 text-center py-4 px-4 rounded-lg"
    >
      <p class="w-full text-center font-semibold text-third">
        There are no results to be shown
      </p>
    </div>
  </div>
  {% endif %}
</div>
<!-- Chart.js library -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<!-- Custom JavaScript code -->
<script>
  document.addEventListener('DOMContentLoaded', function() {
    // Get the data from the server
    var rounds = {{ rounds|safe }};  // Ensure the data is safe for rendering

    // Extract the metrics for each round
    var losses = rounds.map(function(round) {
      return round.losses;
    });

    var trainingAccuracy = rounds.map(function(round) {
      return round.training_accuracy;
    });

    var evaluationAccuracy = rounds.map(function(round) {
      return round.evaluation_accuracy;
    });

    // Chart.js configuration
    var ctxLosses = document.getElementById('lossesChart').getContext('2d');
    var lossesChart = new Chart(ctxLosses, {
      type: 'line',
      data: {
        labels: rounds.map(function(round) {
          return round.round;
        }),
        datasets: [{
          label: 'Losses',
          data: losses,
          borderColor: 'rgba(255, 99, 132, 1)',
          backgroundColor: 'rgba(255, 99, 132, 0.2)',

          fill: true
        }]
      },
      options: {
        // Configure the chart options as desired
      }
    });

    var ctxTrainingAccuracy = document.getElementById('trainingAccuracyChart').getContext('2d');
    var trainingAccuracyChart = new Chart(ctxTrainingAccuracy, {
      type: 'line',
      data: {
        labels: rounds.map(function(round) {
          return round.round;
        }),
        datasets: [{
          label: 'Training Accuracy',
          data: trainingAccuracy,
          borderColor: 'rgba(75, 192, 192, 1)',
          backgroundColor: 'rgba(75, 192, 192, 0.2)',
          fill: true
        }]
      },
      options: {
        // Configure the chart options as desired
      }
    });

    var ctxEvaluationAccuracy = document.getElementById('evaluationAccuracyChart').getContext('2d');
    var evaluationAccuracyChart = new Chart(ctxEvaluationAccuracy, {
      type: 'line',
      data: {
        labels: rounds.map(function(round) {
          return round.round;
        }),
        datasets: [{
          label: 'Test Accuracy',
          data: evaluationAccuracy,
          borderColor: 'rgba(54, 162, 235, 1)',
          backgroundColor: 'rgba(54, 162, 235, 0.2)',
          fill: true
        }]
      },
      options: {
        // Configure the chart options as desired
      }
    });
  });
</script>
{% endblock %}

web/templates/fl/fl-results.html
{% extends 'gui/base/base.html' %} {% load static tailwind_tags %} {% load
i18n%} {% block content %}
<div class="relative max-w-[1440px] w-full lg:min-h-screen-admin">
  <h1 class="text-3xl text-third font-bold text-center">Fl results</h1>

  <p class="mb-4 text-third my-16">
    Federated Learning Results: Our federated learning process utilizes the
    collaborative efforts of hospitals and doctors to train a global model for
    medical health and X-ray image analysis. Through this approach, we have
    achieved remarkable results. During the training phase, each participating
    hospital or doctor trains a local model on their own patient data while
    keeping the data securely on their premises. The local models are then
    aggregated to create the global model, benefiting from the collective
    knowledge of all participants. We have observed impressive training
    accuracy, with the global model achieving an average accuracy of over 90%.
    The testing accuracy has demonstrated excellent performance, consistently
    achieving accuracy rates above 70% in the 3rd round. Additionally, we have
    monitored the loss reduction throughout the training iterations, observing a
    significant decrease in the loss function. These exceptional results reflect
    the power of federated learning in harnessing the collective intelligence of
    healthcare professionals while preserving data privacy and security. Our
    approach enables hospitals and doctors to leverage a shared global model
    that continually learns and improves, leading to enhanced diagnostic
    accuracy and better patient outcomes.
  </p>

  {% if all_results %}
  <table
    class="w-full text-sm text-left text-gray-500 overflow-x-auto shadow-md sm:rounded-lg"
  >
    <thead class="text-xs text-gray-700 uppercase bg-gray-50">
      <tr>
        <th scope="col" class="px-6 py-3">Date</th>
        <th scope="col" class="px-6 py-3">Min number of clients</th>
        <th scope="col" class="px-6 py-3">Number of rounds</th>
        <th scope="col" class="px-6 py-3">Durations</th>
        <th scope="col" class="px-6 py-3">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for result in all_results %}
      <tr
        class="patient-row bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600"
      >
        <td class="px-6 py-4">{{result.result.date}}</td>
        <td class="px-6 py-4">{{result.result.min_client}}</td>
        <td class="px-6 py-4">{{result.result.num_round}}</td>
        <td class="px-6 py-4">{{result.duration}}</td>
        <td class="px-6 py-4">
          <a
            href="{% url 'fl:result' result.result.id %}"
            class="font-medium text-primary hover:underline"
            >Check result</a
          >
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <div
    class="flex items-center jusfity-center bg-gray-100 text-center py-4 px-4 rounded-lg"
  >
    <p class="w-full text-center font-semibold text-third">
      There is no results to be shown
    </p>
  </div>
  {% endif %}
</div>
{% endblock %}