web/Fl_e_health/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("main.urls")),
    path('patients/',include ('patients.urls')),
    path('fl/',include ('fl.urls')),
    path('hospital/',include ('hospital.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/fl/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.decorators import login_required


app_name = 'fl'

urlpatterns = [
    path('', login_required(FlHome.as_view()), name="fl"),
    path('results/', login_required(FlResultsView.as_view()), name="results"),
    path('results/<int:pk>/', login_required(FlResultView.as_view()), name="result"),
]

web/hospital/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.decorators import login_required

app_name = 'hospital'


urlpatterns = [
    path('list-doctors/', login_required(ListOfDoctors.as_view()), name="list-doctors"),
    path('add-doctor/', login_required(AddDoctor.as_view()), name="add-doctor"),
    path('edit-doctor/<int:doctor_id>/', login_required(EditDoctor.as_view()), name="edit-doctor"),
    
]

web/patients/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.decorators import login_required


app_name = 'patients'

urlpatterns = [
    path('add-patient/', login_required(AddPatient.as_view()), name="add-patient"),
    path('<int:patient_id>/edit-patient/', login_required(EditPatient.as_view()), name="edit-patient"),
    path('my-patients/', login_required(MyPatient.as_view()), name="my-patients"),
    path('xray-image/<int:patient_id>/add-xray-image', login_required(AddXrayImageView.as_view()), name='add-xray-image'),
    path('xray-image/edit-xray-image/<int:xray_image_id>', login_required(EditXrayImageView.as_view()), name='edit-xray-image'),
    path('my-patient/archive/',login_required(ArchiveView.as_view()),name="archive"),
    path('makePrediction/', login_required(MakePrediction.as_view()), name='delete-xray-image'),
    path('patient-login/', PatientLoginView.as_view(), name='patient-login'),
    path('patient-result/', PatientResultView.as_view(), name='patient-result'),
]

web/templates/gui/shared/footer.html
{% load static %}

<footer class="bg-primary">
  <div class="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
    <div class="md:flex md:justify-between">
      <div class="mb-6 md:mb-0">
        <a href="https://flowbite.com/" class="flex items-center">
          <img
            src="{% static 'images/icone.png' %}"
            class="h-8 mr-3"
            alt="FlowBite Logo"
          />
          <span
            class="self-center text-2xl font-semibold whitespace-nowrap text-white"
            >Health Hub</span
          >
        </a>
      </div>
      <div class="grid grid-cols-2 gap-8 sm:gap-6 sm:grid-cols-3">
        <div>
          <h2
            class="mb-6 text-sm font-semibold text-gray-900 uppercase text-white"
          >
            Resources
          </h2>
          <ul class="text-white font-medium">
            <li class="mb-4">
              <a href="{% url 'about' %}" class="hover:underline">About</a>
            </li>
            <li>
              <a href="{% url 'contact-us' %}" class="hover:underline"
                >Contact us</a
              >
            </li>
          </ul>
        </div>
        <div>
          <h2 class="mb-6 text-sm font-semibold uppercase text-white">
            Follow us
          </h2>
          <ul class="font-medium text-white">
            <li class="mb-4">
              <a
                href="https://github.com/themesberg/flowbite"
                class="hover:underline"
                >Github</a
              >
            </li>
            <li>
              <a href="https://discord.gg/4eeurUVvTy" class="hover:underline"
                >Discord</a
              >
            </li>
          </ul>
        </div>
        <div>
          <h2
            class="mb-6 text-sm font-semibold text-gray-900 uppercase text-white"
          >
            Legal
          </h2>
          <ul class="text-white font-medium">
            <li class="mb-4">
              <a href="{% url 'privacy' %}" class="hover:underline"
                >Privacy Policy</a
              >
            </li>
            <li>
              <a href="{% url 'terms' %}" class="hover:underline"
                >Terms &amp; Conditions</a
              >
            </li>
          </ul>
        </div>
      </div>
    </div>
    <hr class="my-6 sm:mx-auto border-white lg:my-8" />
    <div class="">
      <span class="text-sm text-white sm:text-center"
        >© 2023
        <a href="https://flowbite.com/" class="hover:underline">Health Hub</a>.
        All Rights Reserved.
      </span>
    </div>
  </div>
</footer>

web/templates/gui/shared/navbar.html
{% load static tailwind_tags %}

<nav class="bg-primary">
  <div
    class="max-w-screen-xl flex flex-row items-center justify-between mx-auto h-[90px]"
  >
    <a href="{% url 'home' %}" class="flex items-center">
      <img
        src="{% static 'images/icone.png' %}"
        class="h-8 mr-3"
        alt="Flowbite Logo"
      />
      <span
        class="self-center text-2xl font-semibold whitespace-nowrap text-white"
        >Health Hub</span
      >
    </a>
    {% if user.is_authenticated %}
    <div class="flex items-center md:order-2">
      <button
        type="button"
        class="flex mr-3 text-sm rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 p-1"
        id="user-menu-button"
        aria-expanded="false"
        data-dropdown-toggle="user-dropdown"
        data-dropdown-placement="bottom"
      >
        {% if user.user_type == "Doctor" %}
        <img
          class="w-10 h-10 rounded-full"
          src="{% static 'images/doctor_illustration.png' %}"
          alt="user photo"
        />
        {% else %}
        <img
          class="w-10 h-10 rounded-full"
          src="{% static 'images/hospital_illustration.png' %}"
          alt="user photo"
        />
        {% endif %}
      </button>
      <!-- Dropdown menu -->
      <div
        class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow bg-gray-700 divide-gray-600"
        id="user-dropdown"
      >
        <div class="px-4 py-3">
          <span class="block text-sm text-gray-900">{{user.username}}</span>
          <span class="block text-sm text-gray-500 truncate text-gray-400"
            >{{user.email}}</span
          >
        </div>
        <ul class="py-2" aria-labelledby="user-menu-button">
          <li>
            <a
              href="{% url 'profile' %}"
              class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:bg-gray-600 text-gray-200 hover:text-white"
              >Profile</a
            >
          </li>
          {% if user.user_type == "Hospital" %}
          <li>
            <a
              href="{% url 'hospital:list-doctors' %}"
              class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:bg-gray-600 text-gray-200 hover:text-white"
              >Doctors list</a
            >
          </li>
          {% else %}
          <li>
            <a
              href="{% url 'patients:my-patients' %}"
              class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:bg-gray-600 text-gray-200 hover:text-white"
              >Patients list</a
            >
          </li>
          {% endif %}

          <li>
            <a
              href="{% url 'signout' %}"
              class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:bg-gray-600 text-gray-200 hover:text-white"
              >Sign out</a
            >
          </li>
        </ul>
      </div>
      <button
        data-collapse-toggle="mobile-menu-2"
        type="button"
        class="inline-flex items-center p-2 ml-1 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 text-gray-400 hover:bg-gray-700 focus:ring-gray-600"
        aria-controls="mobile-menu-2"
        aria-expanded="false"
      >
        <span class="sr-only">Open main menu</span>
        <svg
          class="w-6 h-6"
          aria-hidden="true"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
            clip-rule="evenodd"
          ></path>
        </svg>
      </button>
    </div>
    {% else %}
    <a
      href="{% url 'signin' %}"
      class="inline-flex items-center justify-center px-5 py-3 font-medium text-center border border-white rounded-lg text-primary bg-white hover:text-white hover:bg-primary focus:ring-gray-800 md:order-2"
    >
      Sign In
    </a>
    {% endif %}
    <div
      class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1"
      id="mobile-menu-2"
    >
      <ul
        class="flex flex-col font-medium p-4 md:p-0 mt-4 border rounded-lg md:flex-row md:space-x-8 md:mt-0 md:border-0"
      >
        <li>
          <a
            href="{% url 'home' %}"
            class="block py-2 pl-3 pr-4 text-white rounded text-white hover:text-gray-400"
            aria-current="page"
            >Home</a
          >
        </li>
        <li>
          <a
            href="{% url 'patients:patient-login' %}"
            class="block py-2 pl-3 text-white hover:text-gray-400"
            >Check patient result</a
          >
        </li>
        <li>
          <a
            href="{% url 'about' %}"
            class="block py-2 pl-3 pr-4 text-white hover:text-gray-400"
            >About</a
          >
        </li>

        <li>
          <a
            href="{% url 'contact-us' %}"
            class="block py-2 pl-3 text-white hover:text-gray-400"
            >Contact</a
          >
        </li>
      </ul>
    </div>
  </div>
</nav>