web/Fl_e_health/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("main.urls")),
    path('patients/',include ('patients.urls')),
    path('fl/',include ('fl.urls')),
    path('hospital/',include ('hospital.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/fl/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.decorators import login_required


app_name = 'fl'

urlpatterns = [
    path('', login_required(FlHome.as_view()), name="fl"),
    path('results/', login_required(FlResultsView.as_view()), name="results"),
    path('results/<int:pk>/', login_required(FlResultView.as_view()), name="result"),
]

web/patients/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.decorators import login_required


app_name = 'patients'

urlpatterns = [
    path('add-patient/', login_required(AddPatient.as_view()), name="add-patient"),
    path('<int:patient_id>/edit-patient/', login_required(EditPatient.as_view()), name="edit-patient"),
    path('my-patients/', login_required(MyPatient.as_view()), name="my-patients"),
    path('xray-image/<int:patient_id>/add-xray-image', login_required(AddXrayImageView.as_view()), name='add-xray-image'),
    path('xray-image/edit-xray-image/<int:xray_image_id>', login_required(EditXrayImageView.as_view()), name='edit-xray-image'),
    path('my-patient/archive/',login_required(ArchiveView.as_view()),name="archive"),
    path('makePrediction/', login_required(MakePrediction.as_view()), name='delete-xray-image'),
    path('patient-login/', PatientLoginView.as_view(), name='patient-login'),
    path('patient-result/', PatientResultView.as_view(), name='patient-result'),
]

web/patients/models.py
from django.db import models
from main.models import User
from datetime import date

# Create your models here.


class Patient(models.Model):

    GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )

    BLOOD_TYPE_CHOICES = (
        ('A+', 'A+'),
        ('A-', 'A-'),
        ('B+', 'B+'),
        ('B-', 'B-'),
        ('AB+', 'AB+'),
        ('AB-', 'AB-'),
        ('O+', 'O+'),
        ('O-', 'O-'),
    )

    def __str__(self):
        return self.full_name

    full_name = models.CharField(max_length=200, blank=False, null=False)
    birth_date = models.DateField()
    last_updated = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    created_by = models.ForeignKey(
        User, related_name='patients', on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to="patients", blank=True, null=True)
    description = models.TextField()
    phone_number = models.CharField(max_length=10)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, null=True, blank=True)
    blood_type = models.CharField(max_length=3, choices=BLOOD_TYPE_CHOICES, null=True, blank=True)
    adress = models.CharField(max_length=200, null=True, blank=True)
    username=models.CharField(max_length=50,null=True,blank=True)
    secret_key=models.CharField(max_length=50,null=True,blank=True)
    archived=models.BooleanField(default=False)

    def age(self):
        today = date.today()
        return today.year - self.birth_date.year - ((today.month, today.day) < (self.birth_date.month, self.birth_date.day))

class XrayImage(models.Model):
    type_choices=(
        ("multiclass","multiclass"),
        ("pneumonia","pneumonia")
    )
    patient = models.ForeignKey(Patient, related_name='xray_images', on_delete=models.CASCADE)
    diagnostic = models.CharField(max_length=200, null=True, blank=True)
    xray_image = models.ImageField(upload_to="xray_images", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    type = models.CharField(max_length=10, choices=type_choices,default=type_choices[0][0])

web/patients/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.decorators import login_required
from . models import *
from django.db.models import Q
from django.urls import reverse
from PIL import Image
from django.views.decorators.csrf import csrf_exempt
from django.http import  JsonResponse
import json, requests
from django.conf import settings
from io import BytesIO
from django.core import serializers

# Create your views here.




def patient_detail(request, patient_id):
    patient = get_object_or_404(Patient, id=patient_id)
    xray_images=XrayImage.objects.filter(patient=patient)
    return render(request, 'patients/patient-detail.html', {
        'patient':patient,
        'xray_images':xray_images
    })




class AddPatient(View):
    def get(self,req):
        return render(req, 'gui/patients/add-patient.html')
    
    def post(self, req):
        res = {"status":500, "message": "There was an error please verify the data provided and retry"}
        try:
            print(req.POST)
            full_name=req.POST.get("full_name")
            birth_date=req.POST.get("birth_date")
            phone_number=req.POST.get("phone_number")
            blood_type=req.POST.get("blood_type")
            gender=req.POST.get("gender")
            adress=req.POST.get("adress")
            description=req.POST.get("description")
            username=req.POST.get("username")
            secret_key=req.POST.get("secret_key")
            image=req.FILES['image']
            if full_name and birth_date and phone_number and blood_type and gender and adress and description and image and username and secret_key:
                verify_patient=Patient.objects.filter(username=username)
                if verify_patient:
                    res["status"]=400
                    res["message"]="Patient username exist already please change it !"
                else:
                    Patient.objects.create(full_name=full_name,birth_date=birth_date,created_by=req.user,phone_number=phone_number,blood_type=blood_type,gender=gender,adress=adress,description=description,username=username,secret_key=secret_key,image=image)
                    res["status"]=200
                    res["message"]="Patient created with success"
            else :
                res["status"]=400
                res["message"]="Please retry and verify if there is a missing field or incorrect data"
            
        except Exception as e:
            print(e)
            

        return JsonResponse(res, status=res["status"])


class EditPatient(View):
    def get(self,req,patient_id):
        patient=Patient.objects.filter(id=patient_id).first()
        xray_images=XrayImage.objects.filter(patient=patient)
        return render(req, 'gui/patients/edit-patient.html', {'patient':patient,"xray_images":xray_images
    })
    def post(self,req,patient_id):
        res = {"status": 500, "message": "Une erreur est survenue, veuillez réessayer."}
        try:
            files = req.FILES
            body = req.POST
            data={}
            for key in body:
                data[key] = body[key]
            patient = Patient.objects.filter(id=patient_id).first()
            if patient :
                if patient.created_by == req.user :
                    for attr, value in data.items(): 
                            setattr(patient, attr, value)
                    if files:
                         print(files["image"])
                         patient.image=files["image"]
                    patient.save() 
                    res['status'] = 200
                    res['message'] = "Patient updated with success"
                else :
                    res['status'] = 401
                    res['message'] = "Unauthorized"

        except Exception as e:
            print(e)
        return JsonResponse(res, status = res['status'])
    def delete(self,req,patient_id):
        res = {"status": 500, "message": "Une erreur est survenue, veuillez réessayer."}
        try:
            patient=Patient.objects.filter(id=patient_id).first()
            if patient :
                if patient.created_by == req.user :
                    patient.delete()
                    res["status"]=200
                    res["message"]="Patient deleted with success"
        except Exception as e:
            print(e)
        return JsonResponse(res, status = res['status'])
    
    def put(self,req,patient_id):
        res = {"status": 500, "message": "Une erreur est survenue, veuillez réessayer."}
        try:
            patient=Patient.objects.filter(id=patient_id).first()
            if patient :
                if patient.created_by == req.user :
                    patient.archived=True
                    patient.save()
                    res["status"]=200
                    res["message"]="Patient archived with success"
        except Exception as e:
            print(e)
        return JsonResponse(res, status = res['status'])

    def patch(self,req,patient_id):
        res = {"status": 500, "message": "Une erreur est survenue, veuillez réessayer."}
        try:
            patient=Patient.objects.filter(id=patient_id).first()
            if patient :
                if patient.created_by == req.user :
                    patient.archived=False
                    patient.save()
                    res["status"]=200
                    res["message"]="Patient unarchived with success"
        except Exception as e:
            print(e)
        return JsonResponse(res, status = res['status'])
        



@login_required
def delete_patient(request, patient_id):
    patient = get_object_or_404(Patient, id=patient_id, created_by=request.user)
    patient.delete()
    return redirect('patients:my-patients')

@login_required
def my_patients(request):
    patients = Patient.objects.filter(created_by=request.user)
    return render(request, 'patients/patients-list.html', {
        'patients': patients,
        'title': 'My patients',
    })

class MyPatient(View):
    def get(self,req):
        patients = Patient.objects.filter(created_by=req.user,archived=False)

        return render(req, 'gui/patients/patients-list.html', {
            'patients': patients,
        })
    
class AddXrayImageView(View):
    def get(self,req,patient_id):
        print(patient_id)
        patient=Patient.objects.filter(id=patient_id).first()
        if patient:
            return render(req,"gui/xray/add-xray-image.html",{"patient":patient})
        else :
            return redirect("home")  
        
    def post(self,req,patient_id):
        res = {"status": 500, "message": "Une erreur est survenue, veuillez réessayer."}
        try:
            files = req.FILES
            data = req.POST
            patient=Patient.objects.filter(id=patient_id).first()
            type=data.get("type")
            diagnostic=data.get("diagnostic")
            print(type,diagnostic)
            if patient and type and diagnostic and files :
                xray_image=XrayImage.objects.create(patient=patient,diagnostic=data.get("diagnostic"),xray_image=files["image"],type=data.get("type"))
                res["status"]=200
                res["message"]="Xray image added with success"
            else :
                res["status"]=400
                res["message"]="Please provide all the necessary data !"

            
        except Exception as e:
            print(e)
        return JsonResponse(res, status=res["status"])


class EditXrayImageView(View):
    def get(self,req,xray_image_id):
        xray_image=XrayImage.objects.filter(id=xray_image_id).first()
        return render(req,"gui/xray/edit-xray-image.html",{'xray_image':xray_image})
    
    def post(self,req,xray_image_id):
        res = {"status": 500, "message": "Une erreur est survenue, veuillez réessayer."}
        try:
            files = req.FILES
            data = req.POST
            xray_image=XrayImage.objects.filter(id=xray_image_id).first()

            if data.get("type"):
                xray_image.type=data.get("type")

            if data.get("diagnostic"):
                xray_image.diagnostic=data.get("diagnostic")

            if files:
                xray_image.xray_image=files['image']

            xray_image.save()

            res["status"]=200
            res["message"]="Xray image modified with success"
        except Exception as e:
            print(e)
        return JsonResponse(res, status=res["status"])
    
    def delete(self,req,xray_image_id):
        res = {"status": 500, "message": "Une erreur est survenue, veuillez réessayer."}
        try:
            xray_image=XrayImage.objects.filter(id=xray_image_id).first()
            if xray_image:
                if xray_image.patient.created_by == req.user:
                    xray_image.delete()
                    res["status"]=200
                    res["message"]="Xray image deleted with success"
            
        except Exception as e:
            print(e)
        return JsonResponse(res, status=res["status"])



class ArchiveView(View):
    def get(self,req):
        archived_patients=Patient.objects.filter(created_by=req.user,archived=True)
        return render(req, 'gui/patients/patients-list-archive.html',{"archived_patients":archived_patients})
    def post(self,req):
        pass


@login_required
def delete_xray_image(request, xray_image_id):
    xray_image = get_object_or_404(XrayImage, id=xray_image_id)
    xray_image.delete()
    return redirect('patients:patient-detail', patient_id=xray_image.patient.id)


class MakePrediction(View):
    # img = Image.open("img_dir")
    def post(self,req):
        
        res = {"status": 500, "message": "Une erreur est survenue, veuillez réessayer."}
        try:
            files=req.FILES
            data = req.POST
            print(data)

web/templates/gui/patients/patient-login.html
{% extends 'gui/base/base.html' %} {% load static %} {% block content %}

<section>
  <div
    class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0 min-w-[800px]"
  >
    <a
      href="{% url 'home' %}"
      class="flex items-center mb-6 text-2xl font-semibold text-third"
    >
      <img
        class="w-8 h-8 mr-2"
        src="{% static 'images/icone-primary.png' %}"
        alt="logo"
      />
      Health Hub
    </a>
    <div
      class="w-full bg-white rounded-lg shadow border md:mt-0 sm:max-w-md xl:p-0 border-orange"
    >
      <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
        <h1
          class="text-xl font-bold leading-tight tracking-tigh md:text-2xl text-primary"
        >
          Check your medical folder
        </h1>
        <form
          class="space-y-4 md:space-y-6"
          onsubmit="patientLogin(event, this)"
        >
          <div>
            <label
              for="username"
              class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
              >username</label
            >
            <input
              type="text"
              name="username"
              id="username"
              class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="John123"
              required=""
            />
          </div>
          <div>
            <label
              for="secret_key"
              class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
              >Secret key</label
            >
            <input
              type="password"
              name="secret_key"
              id="secret_key"
              placeholder="••••••••"
              class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              required=""
            />
          </div>
          <button
            class="w-full text-white focus:outline-none font-medium rounded-lg text-sm px-5 py-2.5 text-center focus:ring-primary-800"
            style="background-color: #025464"
          >
            Check
          </button>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

web/templates/gui/patients/patients-list-archive.html
{% extends 'gui/base/base.html' %} {% load static %} {% block content %}

<div class="relative max-w-[1440px] w-full lg:min-h-screen-admin">
  <h1 class="text-3xl text-third font-bold text-center">Archived patient</h1>
  <div
    class="flex items-center justify-end pb-4 bg-white dark:bg-gray-900 mt-8"
  >
    <div class="relative">
      <div
        class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none"
      >
        <svg
          class="w-5 h-5 text-gray-500 dark:text-gray-400"
          aria-hidden="true"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
            clip-rule="evenodd"
          ></path>
        </svg>
      </div>
      <input
        type="text"
        id="search-input"
        class="block p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-80 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
        placeholder="Search for archived users"
        oninput="searchPatients(event,this)"
      />
    </div>
  </div>
  {% if archived_patients %}
  <table
    class="w-full text-sm text-left text-gray-500 dark:text-gray-400 overflow-x-auto shadow-md sm:rounded-lg"
  >
    <thead
      class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"
    >
      <tr>
        <th scope="col" class="p-4">
          <div class="flex items-center">
            <input
              id="checkbox-all-search"
              type="checkbox"
              class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
            />
            <label for="checkbox-all-search" class="sr-only">checkbox</label>
          </div>
        </th>
        <th scope="col" class="px-6 py-3">Name</th>
        <th scope="col" class="px-6 py-3">Blood Type</th>
        <th scope="col" class="px-6 py-3">Birth date</th>
        <th scope="col" class="px-6 py-3">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for patient in archived_patients %}
      <tr
        class="patient-row bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600"
      >
        <td class="w-4 p-4">
          <div class="flex items-center">
            <input
              id="checkbox-table-search-1"
              type="checkbox"
              class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
            />
            <label for="checkbox-table-search-1" class="sr-only"
              >checkbox</label
            >
          </div>
        </td>
        <th
          scope="row"
          class="flex items-center px-6 py-4 text-gray-900 whitespace-nowrap dark:text-white"
        >
          <img
            class="w-10 h-10 rounded-full"
            src="/media/{{patient.image}}"
            alt="Patient image"
          />
          <div class="pl-3">
            <div class="text-base font-semibold" id="full_name">
              {{patient.full_name}}
            </div>
            <div class="font-normal text-gray-500">
              {{patient.phone_number}}
            </div>
          </div>
        </th>
        <td class="px-6 py-4">{{patient.blood_type}}</td>
        <td class="px-6 py-4">
          <div class="flex items-center">{{patient.birth_date}}</div>
        </td>
        <td class="px-6 py-4">
          <a
            href="{% url 'patients:edit-patient' patient.id %}"
            class="font-medium text-light-purple hover:underline"
            >Edit patient</a
          >
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <div
    class="flex items-center jusfity-center bg-gray-100 text-center py-4 px-4 rounded-lg"
  >
    <p class="w-full text-center font-semibold text-third">
      You have no archived patients
    </p>
  </div>
  {% endif %}
</div>

<script>
  function searchPatients(event, elem) {
    event.preventDefault();
    const filter = elem.value.toLowerCase();
    const patientRows = document.querySelectorAll(".patient-row");
    patientRows.forEach(function (row) {
      const name = row.querySelector("#full_name").innerText.toLowerCase();
      if (name.indexOf(filter) > -1) {
        row.style.display = "";
      } else {
        row.style.display = "none";
      }
    });
  }
</script>

<style>
  .patient-row td:first-child {
    border-top-left-radius: 10px;
    border-bottom-left-radius: 10px;
  }

  .patient-row td:last-child {
    border-top-right-radius: 10px;
    border-bottom-right-radius: 10px;
  }

  .patient-row {
    overflow: hidden;
    margin-bottom: 10px;
    background-color: #f2f2f2;
  }

  table {
    border-collapse: separate;
    border-spacing: 0 10px;
  }
</style>
{% endblock %}

web/templates/gui/patients/patients-list.html
{% extends 'gui/base/base.html' %} {% load static %} {% block content %}

<div class="relative max-w-[1440px] w-full lg:min-h-screen-admin">
  <h1 class="text-3xl text-third font-bold text-center">My patient</h1>
  <div
    class="flex items-center justify-between pb-4 bg-white dark:bg-gray-900 mt-8"
  >
    <div class="flex items-center justify-center">
      <a
        href="{% url 'patients:add-patient' %}"
        class="inline-flex items-center text-gray-500 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-3 py-1.5 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700"
      >
        <i class="fa-solid fa-plus text-gray-500 mr-1"></i>
        <span>Add patient</span>
      </a>
      <a
        href="{% url 'patients:archive' %}"
        class="inline-flex ml-4 items-center text-white bg-primary border border-gray-300 focus:outline-none hover:bg-forth focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-3 py-1.5"
      >
        Archived patients
      </a>
    </div>
    <div class="relative">
      <div
        class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none"
      >
        <svg
          class="w-5 h-5 text-gray-500 dark:text-gray-400"
          aria-hidden="true"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
            clip-rule="evenodd"
          ></path>
        </svg>
      </div>
      <input
        type="text"
        id="search-input"
        class="block p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-80 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
        placeholder="Search for users"
        oninput="searchPatients(event,this)"
      />
    </div>
  </div>
  {% if patients %}
  <table
    class="w-full text-sm text-left text-gray-500 dark:text-gray-400 overflow-x-auto shadow-md sm:rounded-lg"
  >
    <thead
      class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"
    >
      <tr>
        <th scope="col" class="p-4">
          <div class="flex items-center">
            <input
              id="checkbox-all-search"
              type="checkbox"
              class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
            />
            <label for="checkbox-all-search" class="sr-only">checkbox</label>
          </div>
        </th>
        <th scope="col" class="px-6 py-3">Name</th>
        <th scope="col" class="px-6 py-3">Blood Type</th>
        <th scope="col" class="px-6 py-3">Birth date</th>
        <th scope="col" class="px-6 py-3">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for patient in patients %}
      <tr
        class="patient-row bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600"
      >
        <td class="w-4 p-4">
          <div class="flex items-center">
            <input
              id="checkbox-table-search-1"
              type="checkbox"
              class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
            />
            <label for="checkbox-table-search-1" class="sr-only"
              >checkbox</label
            >
          </div>
        </td>
        <th
          scope="row"
          class="flex items-center px-6 py-4 text-gray-900 whitespace-nowrap dark:text-white"
        >
          <img
            class="w-10 h-10 rounded-full"
            src="/media/{{patient.image}}"
            alt="Patient image"
          />
          <div class="pl-3">
            <div class="text-base font-semibold" id="full_name">
              {{patient.full_name}}
            </div>
            <div class="font-normal text-gray-500">
              {{patient.phone_number}}
            </div>
          </div>
        </th>
        <td class="px-6 py-4">{{patient.blood_type}}</td>
        <td class="px-6 py-4">
          <div class="flex items-center">{{patient.birth_date}}</div>
        </td>
        <td class="px-6 py-4">
          <a
            href="{% url 'patients:edit-patient' patient.id %}"
            class="font-medium text-light-purple hover:underline"
            >Edit patient</a
          >
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <div
    class="flex items-center jusfity-center bg-gray-100 text-center py-4 px-4 rounded-lg"
  >
    <p class="w-full text-center font-semibold text-third">
      You have no patients
    </p>
  </div>
  {% endif %}
</div>

<script>
  function searchPatients(event, elem) {
    event.preventDefault();
    const filter = elem.value.toLowerCase();
    const patientRows = document.querySelectorAll(".patient-row");
    patientRows.forEach(function (row) {
      const name = row.querySelector("#full_name").innerText.toLowerCase();
      if (name.indexOf(filter) > -1) {
        row.style.display = "";
      } else {
        row.style.display = "none";
      }
    });
  }
</script>

<style>
  .patient-row td:first-child {
    border-top-left-radius: 10px;
    border-bottom-left-radius: 10px;
  }

  .patient-row td:last-child {
    border-top-right-radius: 10px;
    border-bottom-right-radius: 10px;
  }

  .patient-row {
    overflow: hidden;
    margin-bottom: 10px;
    background-color: #f2f2f2;
  }

  table {
    border-collapse: separate;
    border-spacing: 0 10px;
  }
</style>

{% endblock %}